class_names = {
 'Ayam Bakar': 0,
 'Ayam Betutu': 1,
 'Ayam Pop': 2,
 'Bakso': 3,
 'Bakwan': 4,
 'Batagor': 5,
 'Beberuk Terong': 6,
 'Capcay': 7,
 'Coto Makasar': 8,
 'Dendeng Batokok': 9,
 'Gado-gado': 10,
 'Gudeg': 11,
 'Gulai Ikan': 12,
 'Gulai Tambusu': 13,
 'Gulai Tunjang': 14,
 'Kerak Telur': 15,
 'Kue Dadar Gulung': 16,
 'Mie Aceh': 17,
 'Nasi Kuning': 18,
 'Papeda': 19,
 'Pempek': 20,
 'Peuyeum': 21,
 'Rawon': 22,
 'Rendang': 23,
 'Sate': 24,
 'Sate Lilit': 25,
 'Soto Banjar': 26,
 'Soto Lamongan': 27,
 'Tahu Sumedang': 28
 }